# -*- coding: utf-8 -*-
"""Proxycurl_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/PradipNichite/Youtube-Tutorials/blob/main/Proxycurl_API.ipynb

###Proxycurl API is a LinkedIn Profile Scraping API

**Use Cases:**

Building Data Driven Applications. (Lead Generation, Prospecting etc)

Eg. Leveraging NLP like GPT-3 to Write Personalize Email , Message, LinkedIn Invitation based on their profile info like Occuption, Experince, Summary etc

https://nubela.co/proxycurl/linkedin
"""

import requests
api_endpoint = 'https://nubela.co/proxycurl/api/v2/linkedin'
linkedin_profile_url = 'https://www.linkedin.com/in/pradipnichite/'
api_key = ''
headers = {'Authorization': 'Bearer ' + api_key}

response = requests.get(api_endpoint,
                        params={'url': linkedin_profile_url,'skills': 'include'},
                        headers=headers)

profile_data = response.json()
profile_data

"""API Documentation : https://nubela.co/proxycurl/docs#people-api-person-profile-endpoint"""

profile_data.keys()

profile_data['full_name']

profile_data['occupation']

profile_data['headline']

print(profile_data['summary'])

profile_data['experiences']

profile_data['experiences'][2]

profile_data['education']

profile_data['education'][0]

profile_data['skills']

